### ISSUE TITLE
v1: Example workflow #1

### ISSUE THREAD

**Issue by jluudev** [jluudev/arthurslastcrusade#7]
# Implement Example Workflow #1 from ExampleFlows.md

## Implement the endpoints from below:
- ## 1. Recruiting a Hero to Guild Example Flow
  Mages Only wants to recruit a new hero into their guild because they need more power to clear the dungeons. First, they check the entire world of heroes by `GET /world/view_heroes/{world_id}`. Mages Only sees that Elminster the Sage is not currently in a guild and that they had enough gold to recruit him. Mages Only wants to recruit Elminster the Sage because he's super powerful and having him would definitely increase their guild rank and gold. 
  
  Mages Only then makes a request to Elminster the Sage.
  
  To do so:
  - Mages Only then sends a request to Elminster the Sage by calling `POST /guild/recruit_hero/{guild_id}/` with Elminster the Sage as the hero name.
  - Elminster the Sage calls `GET /hero/view_pending_requests/{hero_id}` one day because he is not in a guild. He sees the request from Mages Only.
  - Elminster the Sage then has the option to accept by calling `POST /hero/accept_request/{hero_id}/` with the Mages Only as the request input

**Comment by jenchan88** [comment]
monster

**Comment by jenchan88** [comment]
GET /world/view_heroes/{world_id}

**Comment by JefferNg** [comment]
GET /hero/view_pending_requests/{hero_id}

**Comment by titanic-torti** [comment]
POST /hero/accept_request/{hero_id}/

**Comment by jluudev** [comment]
POST /guild/recruit_hero/{guild_id}/
